spring:
  profiles:
#    active: local
#    include: oauth-local, aws-local
    include: oauth, aws
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

file:
  dir: ${FILE_DIR}