spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${{secrets.KAKAO_CLIENT_ID}}
            redirect-uri: https://sicksago.herokuapp.com/oauth/kakao
            client-authentication-method: POST
            client-secret: ${{secrets.KAKAO_CLIENT_SECRET}}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: secret
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000