# postgreSQL & JPA
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mating
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace