spring:
  profiles:
    active: local  #배포 서버에서는 삭제
    include: oauth-local #배포 서버 oauth 로 변경
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

file:
  dir: /Users/gimdohun/Desktop/myProject/uploadFile/