spring:
  profiles:
    include: oauth
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/mate
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug

file:
  dir: /Users/gimdohun/Desktop/myProject/uploadFile/