spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9719a3774e9f6f5c36f7e5da3a2b4005
            redirect-uri: http://localhost:3000/oauth/kakao
            client-authentication-method: POST
            client-secret: y6PhdneXqV6oXXyDPFqSiTLMsEDsnrkd
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: dasjdklasjkldjlasasd12302180djlaj312321dsadajlsdsad
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000